"""add recording self_absent and other_reaction_2 columns

Revision ID: 4e7abdb2a654
Revises: c4c71cf0d37c
Create Date: 2026-08-16 02:46:37.134061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7abdb2a654'
down_revision: Union[str, Sequence[str], None] = 'c4c71cf0d37c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default needed: existing rows must get a value for these NOT
    # NULL columns (autogenerate doesn't add this on its own).
    op.add_column(
        'recordings', sa.Column('self_absent', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column('recordings', sa.Column('other_reaction_2', sa.Text(), nullable=True))
    op.add_column(
        'recordings', sa.Column('reaction_2_ready', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.alter_column('recordings', 'self_absent', server_default=None)
    op.alter_column('recordings', 'reaction_2_ready', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'reaction_2_ready')
    op.drop_column('recordings', 'other_reaction_2')
    op.drop_column('recordings', 'self_absent')
    # ### end Alembic commands ###
