"""add recording single_speaker_detected column

Revision ID: c4c71cf0d37c
Revises: e854702453ad
Create Date: 2026-08-12 20:43:06.246464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c71cf0d37c'
down_revision: Union[str, Sequence[str], None] = 'e854702453ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default needed: existing rows must get a value for this NOT
    # NULL column (autogenerate doesn't add this on its own).
    op.add_column(
        'recordings',
        sa.Column('single_speaker_detected', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('recordings', 'single_speaker_detected', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'single_speaker_detected')
    # ### end Alembic commands ###
