"""add recording current_stage column

Revision ID: e854702453ad
Revises: ea49945eaef2
Create Date: 2026-08-12 20:17:12.611093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e854702453ad'
down_revision: Union[str, Sequence[str], None] = 'ea49945eaef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('current_stage', sa.Enum('ANALYZING_CONVERSATION', 'SEPARATING_SPEAKERS', 'GENERATING_REPORT', name='analysisstage', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'current_stage')
    # ### end Alembic commands ###
